kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nodejs-pipeline-ci-cd"
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift/Jenkinsfile
      env:
        - name: DEV_PROJECT 
          value: ci-development
        - name: STAGE_PROJECT
          value: ci-development
        - name: PROD_PROJECT
          value: ci-development
        - name: APP_NAME
          value: simple-nodejs-app
  source:
    type: Git
    git:
      uri: 'https://github.com/vladsancira/nodejs-tekton.git'
  triggers:
    - type: GitLab
      gitlab:
        secretReference:
          name: gitlabkey
