apiVersion: v1
kind: Secret
metadata:
  name: owm-secret-api
type: Opaque
data:
  OWM_API_KEY: NmIwYzJlN2U4Y2NlZThmODJhMWEyN2QwZDRiODY4NGM=
---

apiVersion: v1
kind: Secret
metadata:
  name: authors-secret-api
type: Opaque
data:
  AUTHORS_API_KEY: YW5hYXJlbWVyZXNpcGVyZQ==