apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  resources:
    - name: nodejs-git
      type: git
    - name: nodejs-image
      type: image

  params:
    - name: APP_NAME
      description: The name of the application
      default: nodejs-tekton
      type: string
    - name: APP_VERSION
        description: The version of the application
        default: 1.0
        type: string
    - name: DB_SECRET_CREDENTIALS
        description: The OCP secret that contains DB credentials
        default: db-secret-credentials
        type: string

  tasks:
  - name: build
    taskRef:
      name: s2i-nodejs
    resources:       
      inputs:
        - name: source
          resource: nodejs-git
      outputs:
        - name: image
          resource: nodejs-image

  - name: deploy-to-dev
    taskRef:
      name: deploy-nodejs-app
    runAfter:
      - build
    resources:
      inputs:
        - name: image
          resource: nodejs-image
      params:
        - name: APP_NAME
          value: "$(params.APP_NAME)"
        - name: APP_VERSION
          value: "$(params.APP_VERSION)"
        - name: DB_SECRET_CREDENTIALS
          value: "$(params.DB_SECRET_CREDENTIALS)"

  - name: promote-to-stage
    taskRef:
      name: promote-nodejs-app
    runAfter:
      - build
    resources:
      params:
        - name: IMAGE_TAG_1
          value: dev
        - name: IMAGE_TAG_2
          value: stage