apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: promote-nodejs-app
spec:
  inputs:
    params:
      - name: APP_NAME
        description: The name of the application
        default: nodejs-tekton
        type: string
      - name: IMAGE_TAG_1
          description: The environment tag
          default: dev
          type: string
      - name: IMAGE_TAG_2
          description: The environment tag
          default: stage
          type: string
  steps:
      - name: image-tag
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc is tag $(inputs.params.APP_NAME):$(inputs.params.IMAGE_TAG_1) $(inputs.params.APP_NAME):$(inputs.params.IMAGE_TAG_2)