apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  resources:
    - name: nodejs-git
      type: git
    - name: nodejs-image
      type: image

  params:
    - name: DEPLOY_ENVIRONMENT
      description: The environment where you deploy the app
      default: 'env-dev'

  tasks:
  - name: build
    taskRef:
      name: build-nodejs-app
    resources:
      inputs:
        - name: source
          resource: nodejs-git
      outputs:
        - name: image
          resource: nodejs-image

  - name: deploy
    taskRef:
      name: deploy-nodejs-app
    runAfter:
      - build
    params:
      - name: DEPLOY_ENVIRONMENT
        value: "$(params.DEPLOY_ENVIRONMENT)"
    resources:
      inputs:
        - name: source
          resource: nodejs-git